package com.sun.autoGenerated;

import java.io.IOException;
import java.sql.SQLException;

import freemarker.template.TemplateException;

public class AutoGeneration {

	public static void main(String[] args) throws ClassNotFoundException, SQLException, IOException, TemplateException {
		// 数据库地址
		String url = "jdbc:mysql://10.17.2.170:3306/phriskmgmt_db";
		// 用户名
		String name = "root";
		// 密码
		String passWord = "Root@123";
		// 驱动
		String driver = "com.mysql.jdbc.Driver";
		// 表名
		String tableName = "t_phrisk_mgmt_result";
		// 模板路径
		String templateDir = "E:\\work\\xiaoniu\\sourceCode\\lib";
		// 生成文件路径
		String autoGeneratedFile = "E:\\sourceCode\\autoGenerated";
		// 实例化
		AutoGenerationJavaCode autoGenerationJavaCode = new AutoGenerationJavaCode(url, name, passWord, driver,
				tableName, autoGeneratedFile, templateDir);

		// 调用生成java代码方法
		autoGenerationJavaCode.autoGenerationJavaCode();
	}

}
