package com.sun.autoGenerated;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;

import freemarker.template.TemplateException;

public class AutoGeneration {

	public static void main(String[] args) throws ClassNotFoundException, SQLException, IOException, TemplateException {
		File file=new File("");
		String filePath = file.getAbsolutePath();
		
		// 数据库地址
		String url = "jdbc:mysql://10.17.2.170:3306/bill_db";
		// 用户名
		String name = "root";
		// 密码
		String passWord = "Root@123";
		// 驱动
		String driver = "com.mysql.jdbc.Driver";
		// 表名
		String tableName = "am_balance";
		// 模板路径
		String templateDir = filePath+"\\lib";
		// 生成文件路径
		String autoGeneratedFile = filePath+"\\source";
		// 实例化
		AutoGenerationJavaCode autoGenerationJavaCode = new AutoGenerationJavaCode(url, name, passWord, driver,
				tableName, autoGeneratedFile, templateDir);

		// 调用生成java代码方法
		autoGenerationJavaCode.autoGenerationJavaCode();
	}

}
